# Generated by Django 4.1.13 on 2024-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('ended', 'Ended')], default='waiting', max_length=12)),
                ('winner', models.TextField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
