# Generated by Django 5.1 on 2024-08-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('display_name', models.TextField(max_length=100)),
                ('rank', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], default='beginner', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
